### ISSUE TITLE
no giphy integration?

### ISSUE THREAD

**Issue by taboularasa** [jdwolk/heyleo#1]
Hi there, I would like to use your open source library but I can't seem to see anything in the readme that explains how to use this with giphy. 

p.s. any chance of this getting ported to js soon? I need it to be rofl before I can use it.

**Comment by jdwolk** [comment]
@taboularasa No giphy integration on the current roadmap toward 1.0 release. Will reconsider other integrations thereafter.

p.s. rofl? [~ 31,000 requests / second](http://www.yesodweb.com/blog/2014/02/new-warp) rofl enough for ya?

**Comment by taboularasa** [comment]
@jdwolk re: giphy integration, fine I'll wait for V2.0, re: rofl, well I don't know... what if I need to handle 32,000 request / second sometimes? then what?

**Comment by pgdaniel** [comment]
:+1: giphy
